In [12]:
import numpy as np

 http://www.labri.fr/perso/nrougier/teaching/numpy.100/


In [6]:
zero = np.zeros(10)
print zero

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [7]:
zero[4] = 1
print zero

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [8]:
array = np.arange(10,50)
print array

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
reshape = np.arange(9).reshape(3,3)
print reshape

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
identity = np.eye(3)
print identity

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [16]:
minandmax = np.random.random((10,10))
mini, maxi = minandmax.min(), minandmax.max()
print mini, maxi

0.00978865134844 0.998908421111


In [17]:
dotproduct = np.dot(np.ones((5,3)), np.ones((3,2)))
print dotproduct

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [18]:
z = np.random.random(10)
z.sort()
print z

[ 0.30898106  0.48463565  0.5198941   0.53731423  0.686432    0.71311275
  0.73975183  0.75817984  0.91032792  0.98199492]
